document.write("My name is Dilibe Fidelugwuowo")
document.write("I am 6.3 foot tall")
document.write("The nameof my country is Nigeria")
// let a = body.createElement("h1")
// a.innerHTML("My name is Dilibe Fidelugwuowo\nI am 6.3 foot tall\nThe name of ny country is Nigeria")
// window.body.table.append(a)